INSERT INTO public.illness (id, name, graft) VALUES (1, 'бешенство', 'прививка от бешенства');
INSERT INTO public.illness (id, name, graft) VALUES (2, 'лептаспириоз', 'антитела');
INSERT INTO public.illness (id, name, graft) VALUES (3, 'гастроэнтерит', 'не требуется');
INSERT INTO public.illness (id, name, graft) VALUES (4, 'бруцеллёз', 'антибиотики');
INSERT INTO public.illness (id, name, graft) VALUES (5, 'лептаспироз', 'антибиотики');
INSERT INTO public.illness (id, name, graft) VALUES (6, 'брадзот', 'антитела');
INSERT INTO public.illness (id, name, graft) VALUES (7, 'чума', 'не требуется');
INSERT INTO public.illness (id, name, graft) VALUES (8, 'токсоплазмоз', 'антибиотики');
INSERT INTO public.illness (id, name, graft) VALUES (9, 'энтерит', 'прививка от энтерита');
INSERT INTO public.illness (id, name, graft) VALUES (10, 'гетерохромия', 'не требуется');